defaults: &defaults
  api:
    port: 3000

  logger:
    name: General Management API
    level: debug
    levels:
      trace:
      debug: STDOUT
      info:
      warn:
      error: STDERR
      fatal:

  database:
    host: localhost
    port: 3306
    user: root
    password: password
    database: "general-management"

development:
  <<: *defaults

production:
  <<: *defaults

  logger:
    level: debug
    levels:
      trace:
      debug: STDOUT
      info: ./log/info.log
      warn: ./log/warn.log
      error: ./log/error.log
      fatal: ./log/fatal.log
